### ISSUE TITLE
Failed (error code 13) - DOUBLEAGENT_STATUS_DOUBLEAGENT_VERIFIER_INSTALL_COPYFILEW_FAILED_X86 on fresh compile

### ISSUE THREAD

**Issue by JABirchall** [Cybellum/DoubleAgent#10]
I just downloaded the code and compiled a fresh bin to test it out. But I keep getting the error 13 `DOUBLEAGENT_STATUS_DOUBLEAGENT_VERIFIER_INSTALL_COPYFILEW_FAILED_X86` even when freshly compiled both x64 and x86 versions.

I made a video to show I followed the 4 easy steps to try the cmd demo: https://www.youtube.com/watch?v=RLrNpo79W5w

**Comment by MichaelEngstlerCB** [comment]
This error indicates that the install command failed to copy the DoubleAgent DLL to SysWOW64.
This probably happens because you already have a previous DoubleAgent DLL in SysWOW64 which is currently in use and therefore is locked and cannot be replaced.
I suggest trying to find out [who is locking the file](https://superuser.com/a/117908) and closing the process that causes the lock.

Worst case scenario, restart your machine and manually delete the DoubleAgent DLLs from SysWOW64 and System32.
