### ISSUE TITLE
no x86 compiled

### ISSUE THREAD

**Issue by moaeddy** [Cybellum/DoubleAgent#9]
i build a solution using VS 2017, but no x86 build just x64 and i ran build solution two times as stated in your README.md

even when testing DoubleAgent_x64.exe on windows 10 i got *Failed (error code 13)*

am i doing something wrong at a point?

**Comment by MichaelEngstlerCB** [comment]
1. Documentation clearly states you must build twice, **once in x86 and once in x64**.
2. You can troubleshoot errors by checking its reason [here](https://github.com/Cybellum/DoubleAgent/blob/master/DoubleAgentShared/Status.h).
Error code 13 (DOUBLEAGENT_STATUS_DOUBLEAGENT_VERIFIER_INSTALL_COPYFILEW_FAILED_X86) probably happened because you didn't build the solution in x86 .

**Comment by moaeddy** [comment]
i was able to get it to work, but my file did not execute after getting below image outcome

![doubt](https://user-images.githubusercontent.com/7292467/30327669-bd3b1dd8-9781-11e7-804c-356a03c43d22.png)

any idea what is missing here?
